framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        routing:
            # Domain Events - async
            App\Core\User\Domain\Event\UserCreatedEvent: async
            App\Core\Invoice\Domain\Event\InvoiceCreatedEvent: async
            App\Core\Invoice\Domain\Event\InvoiceCanceledEvent: async

            # Commands - sync
            App\Core\User\Application\Command\CreateUser\CreateUserCommand: sync
            App\Core\User\Application\Command\ActivateUser\ActivateUserCommand: sync
            App\Core\Invoice\Application\Command\CreateInvoice\CreateInvoiceCommand: sync

            # Queries - sync
            App\Core\User\Application\Query\GetInactiveUsersEmails\GetInactiveUsersEmailsQuery: sync
            App\Core\Invoice\Application\Query\GetInvoicesByStatusAndAmountGreater\GetInvoicesByStatusAndAmountGreaterQuery: sync
